import io.gitlab.arturbosch.detekt.Detekt
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.aboutLibraries)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.composePwa)
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt)
}

spotless {
    kotlin {
        target("**/*.kt")
        targetExclude("**/build/**")
        ktlint()
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
    // HTML / CSS / JS / JSON web resources via Prettier.
    // Excluded because they are rewritten/regenerated by the build, so formatting
    // them would only create churn:
    //  - aboutlibraries.json: regenerated by exportLibraryDefinitions.
    //  - index.html: rewritten in place every build by the composePwa plugin
    //    (AddNecessaryHtmlTags re-serializes it via Jsoup).
    format("web") {
        target(
            "src/webMain/resources/**/*.html",
            "src/webMain/resources/**/*.css",
            "src/webMain/resources/**/*.js",
            "workbox-config-for-wasm.js",
            "src/**/*.json",
        )
        targetExclude("**/build/**", "**/aboutlibraries.json", "**/index.html")
        prettier("3.8.3")
    }
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
}

tasks.register("detektAll") {
    group = "verification"
    description = "Runs detekt on all KMP source sets."
    dependsOn(tasks.withType<Detekt>())
}

// Don't analyze generated sources (e.g. Compose resource accessors live under
// a `.../generated/resources/` path). A string pattern keeps this compatible
// with the configuration cache (a Spec lambda would capture the build script).
tasks.withType<Detekt>().configureEach {
    exclude("**/generated/**")
}

kotlin {
    // The custom .dependsOn() wiring below (uiSharedTest) stops Kotlin from applying
    // the default hierarchy template automatically, which silently drops the webMain
    // source set — and with it src/webMain/resources (index.html, the PWA assets) and
    // the web Main.kt. Apply the template explicitly so webMain keeps existing.
    applyDefaultHierarchyTemplate()

    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }

        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        mainRun {
            mainClass.set("dev.yuyuyuyuyu.toleet.MainKt")
        }
    }

    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.aboutlibraries.compose.m3)
            implementation(compose.materialIconsExtended)
            implementation(libs.jetbrains.navigation3.ui)
            implementation(libs.jetbrains.material3.adaptiveNavigation3)
            implementation(libs.jetbrains.lifecycle.viewmodelNavigation3)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.simpleTopAppBar)
            implementation(libs.myMaterialTheme)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
        }
        // Compose UI tests run on both jvm (desktop) and wasmJs — both detect
        // Compose nodes at runtime (verified on Compose Multiplatform 1.12). They
        // are written once in this intermediate source set and shared by jvmTest
        // and wasmJsTest. The js target cannot host them (its test runtime fails),
        // so it is intentionally excluded; commonTest stays UI-free and runs on
        // every target, including js.
        val uiSharedTest by creating {
            dependsOn(commonTest.get())
            dependencies {
                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                implementation(compose.uiTest)
            }
        }
        jvmTest.get().dependsOn(uiSharedTest)
        wasmJsTest.get().dependsOn(uiSharedTest)
    }
}

compose.desktop {
    application {
        mainClass = "dev.yuyuyuyuyu.toleet.MainKt"
    }
}
