build:
  maxIssues: 0

config:
  validation: true

style:
  active: true
  UnusedImports:
    active: true
  UnusedParameter:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  UnusedPrivateProperty:
    active: true
